---
baseURL: https://dobhaipipes.netlify.app/
languageCode: en-us
title: Do Bhai Pipes
theme: piko
paginate: "9"
copyright: A template by [Heksagon](https://www.heksagon.net "Your most friendly developer")
googleAnalytics: # Enter Google Analytics ie. UA-012345678-9
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
outputs:
  home:
  - HTML
  - RSS
  - JSON
minify:
  disableCSS: false
  disableHTML: false
  disableJS: false
  disableJSON: false
  disableSVG: false
  disableXML: false
  minifyOutput: true
  tdewolff:
    html:
      keepWhitespace: false

params:
  analytics:
    google:
      SiteVerificationTag: # Google Site Verification
    yandex:
      SiteVerificationTag: # Yandex Site Verification
    bing:
      SiteVerificationTag: # Bing Site Verification
  env: production
  author: Vishrut Vishu
  description: Do Bhai Pipes
  math: false
  images:
  - "/uploads/og.webp"
  label:
    title: _Do Bhai Pipes_
    text: Do Bhai Pipes
    lightNavIcon: /uploads/sun.svg
    darkNavIcon: /uploads/zap.svg
    iconHeight: "35"
    iconWIdth: "35"
  comments: true
  mainSections:
  - blog
  ShowShareButtons: true
  ShowCodeCopyButtons: true
  ShowRelated: true
  CookieNotice: We use cookies to improve your experience on our site and to show
    you relevant advertising.
  CookieLink: /legal/privacy/#cookies-and-web-beacons
  CookieButton: Cookies Policy
  disableAnchoredHeadings: false
  contactFormAction: https://fabform.io/f/f44oYVv # Get link from https://formsubmit.io or https://fabform.io
  assets:
    disableFingerprinting: false
    favicon: /uploads/zap.svg
    favicon16x16: /uploads/zap.svg
    favicon32x32: /uploads/zap.svg
    apple_touch_icon: /uploads/zap.svg
    safari_pinned_tab: /uploads/zap.svg
  ShowReadingTime: true
  ShowBreadCrumbs: true
  homepage:
    # Hero Section
    disableHeroSection: false
    heroUpperTitle: 
    heroTitle: Do Bhai Pipes
    heroDescription: Matour Road Kalayat(Kaithal)
    heroCTAPrimaryText:  Chat On Whatsapp
    heroCTAPrimaryUrl: "https://wa.me/919817847570?text=Hi%2C%20I%20saw%20the%20ad%20for%20your%20pipes%20and%20I'm%20very%20interested%20in%20buying%20it."
    heroCTASecondaryText: Contact Us
    heroCTASecondaryUrl: "/contact/"
    heroBackgroundImage: "/uploads/pipes.jpg"
    # Blog Section
    disableBlogSection: true
    blogTitle: Latest Posts
    blogDescription: 
    seeMoreText: More Posts
    # About Section    
    disableAboutSection: false
    aboutTitle: About
    aboutDescription: 
    aboutImgUrl: "/uploads/VishrutSir.png"
    aboutContent: Vishrut Vishu is a visionary industrialist and the proud owner of a thriving pipe factory. With his passion for excellence and unrivaled determination, he has taken his business to great heights and established a reputation that is second to none. As the head of his company, Vishrut is constantly striving to exceed expectations and deliver high-quality products that meet the needs and demands of his clients. He understands the importance of innovation and has invested heavily in research and development to ensure that his factory remains at the forefront of the industry.
    # Portfolio Section
    disablePortfolioSection: false
    portfolioTitle: Portfolio
    portfolioDescription:
    portfolio:
    - imageUrl: /uploads/1.jpg
      alt: # image alt for better SEO
      description: 
      websiteUrl: #
    - imageUrl: /uploads/3.jpg
      alt: # image alt for better SEO
      description: 
      websiteUrl: #
    - imageUrl: /uploads/2.jpg
      alt: # image alt for better SEO
      description: 
      websiteUrl: #
    - imageUrl: /uploads/5.jpg
      alt: # image alt for better SEO
      description: 
      websiteUrl: #
    - imageUrl: /uploads/4.jpg
      alt: # image alt for better SEO
      description: 
      websiteUrl: #
    - imageUrl: /uploads/6.jpg
      alt: # image alt for better SEO
      description: 
      websiteUrl: #
  # Search Options (https://fusejs.io/)
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: "0"
    distance: "1000"
    threshold: "0.4"
    minMatchCharLength: "0"
    keys:
    - title
    - permalink
    - summary
    - content
  plugins:
    css:
    - link: plugins/css/pico.min.css
    js:
    - link: plugins/js/feather.min.js
menus:
  main: # Main Menu
  - name: Blog
    # title: Posts
    # pre: pen-tool
    url: "/blog"
    weight: "20"
  - name: Search
    title: Search
    pre: search
    url: "/search"
    weight: "30"
  - name: Contact
    title: Contact
    pre: mail
    url: "/contact"
    weight: "40"
  - name: Github
    title: 
    pre: 
    url: https://github.com/heksagonnet/piko
    weight: "50"
  search: # Search page's quick links
  - name: Categories
    title: Categories
    url: "/categories"
    weight: "10"
  - name: Archives
    title: Archives
    url: "/archives"
    weight: "20"
  - name: Tags
    title: Tags
    url: "/tags"
    weight: "30"
